name: Build & Push Docker Image

on:
  push:
    tags: 
    - 'v*'

jobs:

  build_publish_docker_image:

    runs-on: ubuntu-latest
    steps:
        - 
          name: Get version
          id: get_version
          uses: battila7/get-version-action@v2
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: tonyskorik/polyphonic-telegram-bot:${{ steps.get_version.outputs.version-without-v }}
